# Generated by Django 5.2 on 2025-10-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_evidence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
